export default data = [
    {id:"01",
    product_name:"Lenovo IdeaPad Slim 3",
    product_price:700,
    imagepic:"https://m.media-amazon.com/images/I/71iI2wTW56L._SL1500_.jpg",
    product_rating:4,
    },
    {id:"02",
    product_name:"HP Pavilion 14 12th Gen",
    product_price:800,
    imagepic:"https://m.media-amazon.com/images/I/81h346HzqML._SL1500_.jpg",
    product_rating:4,
    },
    {id:"03",
    product_name:"Apple iPhone 13",
    product_price:350,
    imagepic:"https://m.media-amazon.com/images/I/61i8Vjb17SL._SL1500_.jpg",
    product_rating:5,
    },
    {id:"04",
    product_name:"Samsung Galaxy S22",
    product_price:300,
    imagepic:"https://m.media-amazon.com/images/I/71PvHfU+pwL._SL1500_.jpg",
    product_rating:5,
    },
    {
        id: "05",
        product_name: "Redmi Note 11",
        product_price: 230,
        imagepic: "https://m.media-amazon.com/images/I/71Iq9ug6OvL._SL1500_.jpg",
        product_rating: 4,
    },
    {
        id: "06",
        product_name: "Oppo A54",
        product_price: 180,
        imagepic: "https://m.media-amazon.com/images/I/618hM-rT4aS._SL1500_.jpg",
        product_rating: 3,
    },
    {
        id: "07",
        product_name: "Fire-Boltt Visionary",
        product_price: 40,
        imagepic: "https://m.media-amazon.com/images/I/61n1X3niLuL._SL1500_.jpg",
        product_rating: 5,
    },
    {
        id: "08",
        product_name: "Noise ColorFit Pulse",
        product_price: 30,
        imagepic: "https://m.media-amazon.com/images/I/61L7mz0jjeL._SL1500_.jpg",
        product_rating: 4,
    },
    {
        id: "09",
        product_name: "boAt Xtend Smartwatch",
        product_price: 70,
        imagepic: "https://m.media-amazon.com/images/I/61IMRs+o0iL._SL1500_.jpg",
        product_rating: 3,
    },
    {
        id: "10",
        product_name: "Vu 190 cm (75 inches)",
        product_price: 900,
        imagepic: "https://m.media-amazon.com/images/I/71hRCyKB-OL._SL1500_.jpg",
        product_rating: 5,
    }
]
